### ISSUE TITLE
Updare README to be based on BCF API v2.2

### ISSUE THREAD

**Issue by leosobral** [buildingSMART/foundation-API#11]
README states that Version 1.0 is based on BCF 2.1 (It should be 2.2).

**Comment by ykulbak** [comment]
@leosobral it is based on BCF 2.1; BCF 2.2 no longer has any reference to Foundation endpoints and conventions.

**Comment by leosobral** [comment]
@ykulbak Ok, I see and makes sense. My thinking was that foundation API should be used together with BCF 2.2 and onwards.

I am fine with closing this.
