### ISSUE TITLE
Should the versions service response also provide a URL to the actual service?

### ISSUE THREAD

**Issue by ykulbak** [buildingSMART/foundation-API#2]
/opencde/versions would then be the only standardized endpoint?

**Comment by KevLoh** [comment]
Suggestion return value:

 "version_id": "1.0",
 "detailed_version": "https://github.com/BuildingSMART/BCF-API",
 {
	"api_name": "bcf",
	"api_version": "2.1",
	"api_detailed_version": "https://github.com/BuildingSMART/BCF-API",
	"api_server_url": "bcf",
 } ,
  {
	"api_name": "documents",
	"api_version": "1.0",
	"api_detailed_version": "https://github.com/BuildingSMART/BCF-API",
	"api_server_url": "http://document.server",
 }

So detailed information for each API.

**Comment by ykulbak** [comment]
decided to rename `api_sever_url` to `api_base_url` - and it should be a fully qualified URL
