### ISSUE TITLE
Create an Open API specification in SwaggerHub

### ISSUE THREAD

**Issue by ykulbak** [buildingSMART/foundation-API#20]
- Create a spec
- Link it to github

**Comment by GeorgDangl** [comment]
Link to the WIP spec:
https://app.swaggerhub.com/apis/buildingSMART/OpenCDE-Foundation/1.0

Reviews and feedback welcome😀

**Comment by ykulbak** [comment]
Closing this issue because the Foundation API mostly documents conventions and agreements and the value in swagger is low. There is also a risk that implementers will only look at the swagger spec and not this document missing on 90% of what this standard specifies.
