### ISSUE TITLE
Examples are wrong, they use `redirect_url` instead of `redirect_uri` (i vs l)

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/foundation-API#24]
Note for me: Please also check the docs

**Comment by ykulbak** [comment]
@GeorgDangl the only schema with a `redirect_url` is `dynRegClient_POST.json`; It ends with small case `URL` - the documentation is consistent with the schema. 

It would be preferable if it ended with a small case `URI`. I think that this is rather a small issue which does not, in itself, justify introducing a breaking change. I suggest we defer this to a major version where other breaking changes would be introduced. Do you agree?

**Comment by GeorgDangl** [comment]
I agree, sounds good😀

**Comment by ykulbak** [comment]
Discussed during the review for the 1.1 version. We close it for now since the change in not backward compatible and hence very costly for implementers and the gap in terminology is small.
