### ISSUE TITLE
Support for Authorization Code with PKCE for section 2.2

### ISSUE THREAD

**Issue by venilillkall** [buildingSMART/foundation-API#25]
See https://oauth.net/2/pkce/

**Comment by ykulbak** [comment]
Sep 25th 2023 / Group call discussion summary.

This issue can be addressed by removing the specific OAUTH features mentioned by the Foundation API spec and leave a generic requirement for the server to provide OAUTH certified implementations that require features supported by well-established and supported libraries available for clients to integrate. 

Pasi raised a concerns that for clients this still leaves a risk that servers might diverge in their OAUTH requirements creating a difficulty for clients to have a single, standard authentication flow supported by all servers.

**Comment by LionelOnTech** [comment]
Implemented proposal in https://github.com/buildingSMART/foundation-API/pull/55

**Comment by GeorgDangl** [comment]
Closed with #55
