### ISSUE TITLE
Include projects endpoint in Foundation API

### ISSUE THREAD

**Issue by GeorgDangl** [buildingSMART/foundation-API#30]
We just discovered this in the call about the OpenCDE Documents API.

There, we need a way for users to select projects via the API. We've, for now, said to use the BCF API for this, but not everyone will have the BCF API. So, including the Projects Service from the BCF API (https://github.com/buildingSMART/BCF-API#31-project-services) with just the `GET` part would make sense in the foundations API.

What do you think?

**Comment by ykulbak** [comment]
@GeorgDangl I think its still not clear if the projects endpoint is needed. Perhaps we should discuss this again in the group?

**Comment by GeorgDangl** [comment]
Hey @ykulbak, I agree. Let's discuss it first this Thursday in the OpenCDE meeting, or maybe delay it there and discuss it in the bigger group with BCF next Monday.

**Comment by GeorgDangl** [comment]
I've made a note for the minutes, so we don't miss it.

**Comment by GeorgDangl** [comment]
Consensus is to rather not include the projects endpoint in the Foundations API, since the concept of a _BCF Project_ is not necessarily the same as a _Foundations Project_ for some servers.

Most servers have a concept of a _project_, but then also something like an _issue collection_ (or multiple) for BCF, and the same for documents.

**Comment by ykulbak** [comment]
Discussion notes:

Participants: @GeorgDangl @pasi-paasiala @jasollien @leosobral, Veni Lillkåll, Anssi Auvinen 


```
[  // pagination / sorting? filtering?
    { 
        id: "id"
        name: "name"
        description: "description"
        supported_opencde_apis: [ "docuemnts" ] // supported features
        sub_projects: [ // consider URLs and sub-calls
            {   
                id: "id"
                name: "name"
                description: "description"
                supported_opencde_apis: [ "bcf", "docuemnts", "properties" ]
                sub_projects: [
                    // consider restricting nesting depth
                ]
            },
            {
                id: "id"
                name: "name"
                description: "description"
                supported_opencde_apis: [ "bcf" ]
            }
        ]
    },
    {

    }
]
```

Questions:
1. What about migration path from BCF projectS?
    ? do we "retire" BCF projects at some point ?
    ? Explaining, in the documentation, how the two project lists map to each other (projects having the "BCF" feature would appear in the BCF API project list)

2. Can we provide a project selection UI on the CDE?
    Optional/Mandatory?

3. Assumptions/Limits - 10s, 100s, 1000s of projects dictate different API features to support
    Pagination sorting and filtering are needed if the number of projects is potentially large

**Comment by ykulbak** [comment]
During discussions for release 1.1 we decided to close this issue because we came to understand that for some servers, projects in BCF can be completely different to projects in documents. For instance, some servers may have a project for each "issue board" and a completely different project for each "document repository".
