### ISSUE TITLE
Version Response Example on the readme is missing a comma afer "detailed_version" value.

### ISSUE THREAD

**Issue by vjleo** [buildingSMART/foundation-API#31]
"detailed_version": "https://github.com/buildingSMART/BCF-API/tree/release_2_1" (MISSING COMMA)

**Comment by GeorgDangl** [comment]
Hey @vjleo, thank you, great catch!

There's a PR for this already: https://github.com/buildingSMART/foundation-API/pull/29

**Comment by vjleo** [comment]
Hi @GeorgDangl , sorry about that.

I'm starting to implement a CDE.

Leo

**Comment by GeorgDangl** [comment]
Hey @vjleo, nothing to be sorry about! I meant the thank you sincerely, it's always appreciated to have contributions!

What kind of CDE are you working on? Do you have some more information about that?

We're just in the middle of specifying the OpenCDE Documents API, and there's so far a (very simple) open source example available: https://github.com/Dangl-IT/Dangl.OpenCDE

You can also always get in touch with us directly via opencde@buildingsmart.org.
