### ISSUE TITLE
OAuth example infers server will change redirect URL

### ISSUE THREAD

**Issue by LionelOnTech** [buildingSMART/foundation-API#54]
[OAuth example](https://github.com/buildingSMART/foundation-API/blob/release_1_1/OAuth2Examples.md) infers server will change redirect URL. 

If Callback URL is wrong:
- Callback URL is
`https://YourWebsite.com`
- But should be:
`https://YourWebsite.com/retrieveCode`

If Callback URL is correct:

- Example redirected URL is:
`https://YourWebsite.com/retrieveCode?code=<server_generated_code>&state=<user_defined_string>`
- But should be:
`https://YourWebsite.com?code=<server_generated_code>&state=<user_defined_string>`

**Comment by GeorgDangl** [comment]
Fixed with 1320ca5
