### ISSUE TITLE
Please rename shared-common-API to "foundations API", to avoid confusion

### ISSUE THREAD

**Issue by jasollien** [buildingSMART/foundation-API#7]

**Comment by leosobral** [comment]
This is a duplicate of https://github.com/buildingSMART/shared-common-API/issues/9 :-)

**Comment by ykulbak** [comment]
In the Open cde hackathon it was decided to:
1. Rename to `opencde-foundation-API`
2. Change all `open-cde` and `open cde` references to `opencde`
